CREATE TABLE production_reward_penalty_record (
    record_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    record_no VARCHAR(64) NOT NULL,
    record_type VARCHAR(32) NOT NULL,
    reason_category VARCHAR(64) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    order_id BIGINT NULL,
    node_instance_id BIGINT NULL,
    employee_user_id BIGINT NULL,
    approver_user_id BIGINT NULL,
    department_name VARCHAR(128) NULL,
    description VARCHAR(512) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    approved_at DATETIME(3) NULL,
    effective_at DATETIME(3) NULL,
    UNIQUE KEY uk_reward_penalty_record_no (record_no),
    KEY idx_reward_penalty_type_status (record_type, status),
    KEY idx_reward_penalty_reason (reason_category),
    KEY idx_reward_penalty_order (order_id),
    KEY idx_reward_penalty_node (node_instance_id),
    KEY idx_reward_penalty_employee (employee_user_id),
    KEY idx_reward_penalty_created (created_at)
);
