INSERT INTO workflow_chain (chain_code, chain_name, product_type, version, intake_branch, status)
VALUES
    ('REGULAR_CROWN', '常规冠修复', 'REGULAR_CROWN', 1, 'BOTH', 1),
    ('IMPLANT_RESTORATION', '种植类修复', 'IMPLANT_RESTORATION', 1, 'BOTH', 1),
    ('PRECISION_ATTACHMENT', '精密附件', 'PRECISION_ATTACHMENT', 1, 'BOTH', 1),
    ('TELESCOPIC_CROWN', '套筒冠', 'TELESCOPIC_CROWN', 1, 'IMPRESSION', 1),
    ('VENEER_RESTORATION', '贴面修复', 'VENEER_RESTORATION', 1, 'BOTH', 1),
    ('REMOVABLE_STEEL', '活动件-钢托', 'REMOVABLE_STEEL', 1, 'BOTH', 1),
    ('REMOVABLE_ACRYLIC', '活动件-胶托', 'REMOVABLE_ACRYLIC', 1, 'BOTH', 1),
    ('REMOVABLE_INVISIBLE', '活动件-隐形', 'REMOVABLE_INVISIBLE', 1, 'BOTH', 1),
    ('ORTHODONTICS', '正畸', 'ORTHODONTICS', 1, 'BOTH', 1);

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'REGULAR_CROWN' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'REGULAR_CROWN_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'REGULAR_CROWN_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'REGULAR_CROWN_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REGULAR_CROWN_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'REGULAR_CROWN_0060', '模型接收', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'MODEL'),
    (@chain_id, 'REGULAR_CROWN_0070', '模型入货检验', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0080', '模型检验出货', '取模分支', 80, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0090', '收发出货', '收发', 90, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REGULAR_CROWN_0100', '口扫', '取模分支', 100, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'REGULAR_CROWN_0110', '数据审核', '取模分支', 110, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'REGULAR_CROWN_0120', 'CAD入货检', 'CAD', 120, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0130', 'CAD扫描', 'CAD', 130, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0140', 'CAD确认设计', 'CAD', 140, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0150', 'CAD排版/切削/染色', 'CAD', 150, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0160', '烧结', 'CAD', 160, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0170', 'CAD检验出货', 'CAD', 170, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0180', '车金入货检验', '车金', 180, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0190', '车金出货检验', '车金', 190, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0200', '上瓷入货检验', '上瓷', 200, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0210', '上瓷出货检验', '上瓷', 210, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0220', '车瓷入货检验', '车瓷', 220, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0230', '车瓷形态确认', '车瓷', 230, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0240', '车瓷出货检验', '车瓷', 240, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0250', '上釉', '收尾', 250, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0260', '抛光', '收尾', 260, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REGULAR_CROWN_0270', '质检出货', '收尾', 270, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REGULAR_CROWN_0280', '等待出货', '收尾', 280, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REGULAR_CROWN_0290', '客服核对订单信息及账单', '收尾', 290, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'REGULAR_CROWN_0300', '发货', '收尾', 300, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'IMPLANT_RESTORATION' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'IMPLANT_RESTORATION_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'IMPLANT_RESTORATION_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'IMPLANT_RESTORATION_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'IMPLANT_RESTORATION_0050', '收发出货', '收发', 50, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'IMPLANT_RESTORATION_0060', '印模', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'IMPLANT_RESTORATION_0070', '模型入货检验', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0080', '模型检验出货', '取模分支', 80, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0090', '种植入货检', '种植', 90, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0100', '口扫', '取模分支', 100, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'IMPLANT_RESTORATION_0110', '数据审核', '取模分支', 110, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'IMPLANT_RESTORATION_0120', '打印模型', '取模分支', 120, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'IMPLANT_RESTORATION_0130', '成品基台', '基台分支', 130, 0, 'implant_abutment', 'FINISHED_ABUTMENT', 'BRANCH'),
    (@chain_id, 'IMPLANT_RESTORATION_0140', '客服定基台', '基台分支', 140, 0, 'implant_abutment', 'FINISHED_ABUTMENT', 'REVIEW'),
    (@chain_id, 'IMPLANT_RESTORATION_0150', '种植配基台', '种植', 150, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0160', '个性化基台', '基台分支', 160, 0, 'implant_abutment', 'CUSTOM_ABUTMENT', 'BRANCH'),
    (@chain_id, 'IMPLANT_RESTORATION_0170', 'CAD入货检', 'CAD', 170, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0180', 'CAD设计', 'CAD', 180, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0190', 'CAD切削基台', 'CAD', 190, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0200', '种植研磨基台', '种植', 200, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0210', '种植上部冠设计', '种植', 210, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0220', 'CAD排版/切削/染色', 'CAD', 220, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0230', 'CAD烧结', 'CAD', 230, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0240', 'CAD检验出货', 'CAD', 240, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0250', '车金入货检验', '车金', 250, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0260', '车金出货检验', '车金', 260, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0270', '上瓷入货检验', '上瓷', 270, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0280', '上瓷出货检验', '上瓷', 280, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0290', '车瓷入货检验', '车瓷', 290, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0300', '车瓷形态确认', '车瓷', 300, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0310', '车瓷出货检验', '车瓷', 310, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0320', '上釉', '收尾', 320, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0330', '抛光', '收尾', 330, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'IMPLANT_RESTORATION_0340', '质检出货', '收尾', 340, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'IMPLANT_RESTORATION_0350', '等待出货', '收尾', 350, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'IMPLANT_RESTORATION_0360', '客服核对订单信息及账单', '收尾', 360, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'IMPLANT_RESTORATION_0370', '发货', '收尾', 370, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'PRECISION_ATTACHMENT' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'PRECISION_ATTACHMENT_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'PRECISION_ATTACHMENT_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'PRECISION_ATTACHMENT_0030', '入厂检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'PRECISION_ATTACHMENT_0050', '收发出货', '收发', 50, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'PRECISION_ATTACHMENT_0060', 'CAD入货检', 'CAD', 60, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0070', 'CAD设计', 'CAD', 70, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0080', 'CAD打印金属', 'CAD', 80, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0090', '车金入货检验', '车金', 90, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0100', '车金出货检验', '车金', 100, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0110', '研磨（订配件）', '车金', 110, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0120', '上瓷入货检验', '上瓷', 120, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0130', '上瓷出货检验', '上瓷', 130, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0140', '车瓷入货检验', '车瓷', 140, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0150', '车瓷形态确认', '车瓷', 150, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0160', '车瓷出货检验', '车瓷', 160, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0170', '抛光', '车瓷', 170, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0180', '钢托入货检验', '钢托', 180, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0190', '活动钢托设计', '钢托', 190, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0200', '钢托打印', '钢托', 200, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0210', '钢托打磨/就位', '钢托', 210, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0220', '钢托出货检验', '钢托', 220, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0230', '车金入货检验', '车金配件', 230, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0240', '车金焊接/安装配件', '车金配件', 240, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0250', '车金出货检验', '车金配件', 250, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0260', '上瓷入货检验', '上瓷配件', 260, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0270', '上瓷（上op）', '上瓷配件', 270, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0280', '上瓷出货检验', '上瓷配件', 280, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0290', '胶托入货检验', '胶托', 290, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0300', '排牙', '胶托', 300, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0310', '刻蜡', '胶托', 310, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0320', '充胶', '胶托', 320, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0330', '打磨', '胶托', 330, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0340', '抛光', '胶托', 340, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'PRECISION_ATTACHMENT_0350', '胶托打磨出货检验质检出货', '胶托', 350, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'PRECISION_ATTACHMENT_0360', '等待出货', '收尾', 360, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'PRECISION_ATTACHMENT_0370', '客服核对订单信息及账单', '收尾', 370, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'PRECISION_ATTACHMENT_0380', '发货', '收尾', 380, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'TELESCOPIC_CROWN' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'TELESCOPIC_CROWN_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'TELESCOPIC_CROWN_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'TELESCOPIC_CROWN_0030', '入厂检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'TELESCOPIC_CROWN_0050', '收发出货', '收发', 50, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'TELESCOPIC_CROWN_0060', '模型入货检验', '模型', 60, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0070', '模型检验出货', '模型', 70, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0080', 'CAD入货检', '内冠', 80, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0090', 'CAD内冠设计', '内冠', 90, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0100', 'CAD打印内冠', '内冠', 100, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0110', '车金入货检验', '内冠', 110, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0120', '车金出货检验', '内冠', 120, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0130', 'CAD入货检', '外冠', 130, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0140', 'CAD设计外冠', '外冠', 140, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0150', 'CAD打印外冠', '外冠', 150, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0160', 'CAD出货检', '外冠', 160, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0170', '车金入货检验', '外冠', 170, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0180', '车金研磨/就位冠', '外冠', 180, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0190', '车金出货检', '外冠', 190, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0200', '钢托入货检验', '钢托', 200, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0210', '钢托设计', '钢托', 210, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0220', '钢托打印', '钢托', 220, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0230', '钢托打磨就位', '钢托', 230, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0240', '钢托出货检验', '钢托', 240, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0250', '车金入货检验', '固活焊接', 250, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0260', '车金固+活焊接', '固活焊接', 260, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0270', '车金出货检验', '固活焊接', 270, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0280', '上瓷入货检验', '上瓷', 280, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0290', '上瓷（上op）', '上瓷', 290, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0300', '上光固化', '上瓷', 300, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0310', '上瓷出货检验', '上瓷', 310, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0320', '车瓷入货检验', '车瓷', 320, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0330', '车瓷形态确认', '车瓷', 330, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0340', '车瓷出货检验', '车瓷', 340, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0350', '抛光', '车瓷', 350, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0360', '胶托入货检验', '胶托', 360, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0370', '排牙', '胶托', 370, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0380', '刻蜡', '胶托', 380, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0390', '充胶', '胶托', 390, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0400', '打磨', '胶托', 400, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0410', '抛光', '胶托', 410, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'TELESCOPIC_CROWN_0420', '胶托打磨出货检验', '胶托', 420, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0430', '质检出货', '收尾', 430, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'TELESCOPIC_CROWN_0440', '等待出货', '收尾', 440, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'TELESCOPIC_CROWN_0450', '客服核对订单信息及账单', '收尾', 450, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'TELESCOPIC_CROWN_0460', '发货', '收尾', 460, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'VENEER_RESTORATION' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'VENEER_RESTORATION_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'VENEER_RESTORATION_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'VENEER_RESTORATION_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'VENEER_RESTORATION_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'VENEER_RESTORATION_0060', '模型入货检验', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0070', '模型检验出货', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0080', '收发出货检验', '收发', 80, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0090', '口扫', '取模分支', 90, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'VENEER_RESTORATION_0100', '数据审核', '取模分支', 100, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'VENEER_RESTORATION_0110', '打印模型', '取模分支', 110, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'VENEER_RESTORATION_0120', 'CAD切削', '贴面路线', 120, 0, 'veneer_route', 'CAD_MILLING', 'BRANCH'),
    (@chain_id, 'VENEER_RESTORATION_0130', '车金入货检验', '贴面路线', 130, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0140', '车金就位', '贴面路线', 140, 0, 'veneer_route', 'CAD_MILLING', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0150', '车金出货检验', '贴面路线', 150, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0160', '上瓷入货检验', '贴面路线', 160, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0170', '上瓷烧结', '贴面路线', 170, 0, 'veneer_route', 'CAD_MILLING', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0180', '上瓷出货检验', '贴面路线', 180, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0190', '车瓷入货检验', '贴面路线', 190, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0200', '车瓷', '贴面路线', 200, 0, 'veneer_route', 'CAD_MILLING', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0210', 'CAD设计', '贴面路线', 210, 0, 'veneer_route', 'CAD_MILLING', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0220', '车瓷形态确认', '贴面路线', 220, 1, 'veneer_route', 'CAD_MILLING', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0230', '车瓷出货检验', '贴面路线', 230, 0, 'veneer_route', 'CAD_MILLING', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0240', '上釉', '收尾', 240, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0250', '抛光', '收尾', 250, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0260', '质检出货', '收尾', 260, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0270', 'CAD传统切蜡', '贴面路线', 270, 0, 'veneer_route', 'TRADITIONAL_WAX', 'BRANCH'),
    (@chain_id, 'VENEER_RESTORATION_0280', 'CAD包埋', '贴面路线', 280, 0, 'veneer_route', 'TRADITIONAL_WAX', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0290', 'CAD铸造', '贴面路线', 290, 0, 'veneer_route', 'TRADITIONAL_WAX', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0300', '车金就位', '贴面路线', 300, 0, 'veneer_route', 'TRADITIONAL_WAX', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0310', '上瓷入货检验', '贴面路线', 310, 0, 'veneer_route', 'TRADITIONAL_WAX', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0320', '上瓷', '贴面路线', 320, 0, 'veneer_route', 'TRADITIONAL_WAX', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0330', '上瓷出货检验', '贴面路线', 330, 0, 'veneer_route', 'TRADITIONAL_WAX', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0340', '车瓷入货检验', '贴面路线', 340, 0, 'veneer_route', 'TRADITIONAL_WAX', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0350', '车瓷', '贴面路线', 350, 0, 'veneer_route', 'TRADITIONAL_WAX', 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0360', '车瓷出货检验', '贴面路线', 360, 0, 'veneer_route', 'TRADITIONAL_WAX', 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0370', '上釉', '收尾', 370, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0380', '抛光', '收尾', 380, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'VENEER_RESTORATION_0390', '质检出货', '收尾', 390, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'VENEER_RESTORATION_0400', '等待出货', '收尾', 400, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'VENEER_RESTORATION_0410', '客服核对订单信息及账单', '收尾', 410, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'VENEER_RESTORATION_0420', '发货', '收尾', 420, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'REMOVABLE_STEEL' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'REMOVABLE_STEEL_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'REMOVABLE_STEEL_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'REMOVABLE_STEEL_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_STEEL_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_STEEL_0060', '模型入货检验', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0070', '模型检验出货', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0080', '收发出货检验', '收发', 80, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0090', '口扫', '取模分支', 90, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_STEEL_0100', '数据审核', '取模分支', 100, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'REMOVABLE_STEEL_0110', '打印模型', '取模分支', 110, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'REMOVABLE_STEEL_0120', '钢托入货检验', '钢托', 120, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0130', '钢托画线设计', '钢托', 130, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0140', '扫描', '钢托', 140, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0150', '设计钢托', '钢托', 150, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0160', '打印钢托', '钢托', 160, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0170', '就位', '钢托', 170, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0180', '打磨', '钢托', 180, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0190', '抛光', '钢托', 190, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0200', '钢托出货检验', '钢托', 200, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0210', '选牙排牙', '胶托', 210, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0220', '刻蜡', '胶托', 220, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0230', '充胶', '胶托', 230, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0240', '打磨', '胶托', 240, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0250', '抛光', '胶托', 250, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_STEEL_0260', '质检出货', '收尾', 260, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_STEEL_0270', '等待出货', '收尾', 270, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_STEEL_0280', '客服核对订单信息及账单', '收尾', 280, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'REMOVABLE_STEEL_0290', '发货', '收尾', 290, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'REMOVABLE_ACRYLIC' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'REMOVABLE_ACRYLIC_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0060', '模型接收', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'MODEL'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0070', '模型入货检验', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0080', '模型检验出货', '取模分支', 80, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0090', '收发出货检验', '收发', 90, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0100', '口扫', '取模分支', 100, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0110', '数据审核', '取模分支', 110, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0120', '打印模型', '取模分支', 120, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0130', '选牙排牙', '胶托', 130, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0140', '刻蜡', '胶托', 140, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0150', '充胶', '胶托', 150, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0160', '打磨', '胶托', 160, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0170', '抛光', '胶托', 170, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0180', '质检出货', '收尾', 180, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0190', '等待出货', '收尾', 190, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0200', '客服核对订单信息及账单', '收尾', 200, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'REMOVABLE_ACRYLIC_0210', '发货', '收尾', 210, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'REMOVABLE_INVISIBLE' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'REMOVABLE_INVISIBLE_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0060', '模型接收', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'MODEL'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0070', '模型入货检验', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0080', '模型检验出货', '取模分支', 80, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0090', '收发出货检验', '收发', 90, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0100', '口扫', '取模分支', 100, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0110', '数据审核', '取模分支', 110, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0120', '打印模型', '取模分支', 120, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0130', '复模', '隐形', 130, 0, NULL, NULL, 'MODEL'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0140', '选牙排牙', '隐形', 140, 1, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0150', '刻蜡', '隐形', 150, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0160', '落盒充胶', '隐形', 160, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0170', '打磨', '隐形', 170, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0180', '抛光', '隐形', 180, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0190', '质检出货', '收尾', 190, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0200', '等待出货', '收尾', 200, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0210', '客服核对订单信息及账单', '收尾', 210, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'REMOVABLE_INVISIBLE_0220', '发货', '收尾', 220, 0, NULL, NULL, 'LOGISTICS');

SET @chain_id = (SELECT chain_id FROM workflow_chain WHERE chain_code = 'ORTHODONTICS' AND version = 1);
INSERT INTO workflow_node (chain_id, node_code, process_name, stage_name, step_order, is_optional, branch_group, branch_key, node_category)
VALUES
    (@chain_id, 'ORTHODONTICS_0010', '客户、客服、销售下单', '下单入厂', 10, 0, NULL, NULL, 'ORDER_INTAKE'),
    (@chain_id, 'ORTHODONTICS_0020', '国外件信息检验、翻译，国内件信息检验', '下单入厂', 20, 0, NULL, NULL, 'REVIEW'),
    (@chain_id, 'ORTHODONTICS_0030', '入厂检验、数据技术检验', '下单入厂', 30, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'ORTHODONTICS_0040', '收发入货', '收发', 40, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'ORTHODONTICS_0050', '印模', '取模分支', 50, 0, 'intake', 'IMPRESSION', 'INTAKE_BRANCH'),
    (@chain_id, 'ORTHODONTICS_0060', '模型接收', '取模分支', 60, 0, 'intake', 'IMPRESSION', 'MODEL'),
    (@chain_id, 'ORTHODONTICS_0070', '模型入货检验', '取模分支', 70, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'ORTHODONTICS_0080', '模型检验出货', '取模分支', 80, 0, 'intake', 'IMPRESSION', 'CHECK'),
    (@chain_id, 'ORTHODONTICS_0090', '收发出货检验', '收发', 90, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'ORTHODONTICS_0100', '口扫', '取模分支', 100, 0, 'intake', 'SCAN', 'INTAKE_BRANCH'),
    (@chain_id, 'ORTHODONTICS_0110', '数据审核', '取模分支', 110, 0, 'intake', 'SCAN', 'REVIEW'),
    (@chain_id, 'ORTHODONTICS_0120', '打印模型', '取模分支', 120, 0, 'intake', 'SCAN', 'MODEL'),
    (@chain_id, 'ORTHODONTICS_0130', 'CAD设计', '正畸', 130, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'ORTHODONTICS_0140', '打磨就位', '正畸', 140, 0, NULL, NULL, 'PRODUCTION'),
    (@chain_id, 'ORTHODONTICS_0150', '质检出货', '收尾', 150, 0, NULL, NULL, 'CHECK'),
    (@chain_id, 'ORTHODONTICS_0160', '等待出货', '收尾', 160, 0, NULL, NULL, 'LOGISTICS'),
    (@chain_id, 'ORTHODONTICS_0170', '客服核对订单信息及账单', '收尾', 170, 0, NULL, NULL, 'BILLING'),
    (@chain_id, 'ORTHODONTICS_0180', '发货', '收尾', 180, 0, NULL, NULL, 'LOGISTICS');

INSERT INTO workflow_edge (chain_id, from_node_id, to_node_id, edge_type, condition_key)
SELECT
    from_node.chain_id,
    from_node.node_id,
    to_node.node_id,
    CASE WHEN to_node.branch_group IS NULL THEN 'SEQUENCE' ELSE 'BRANCH' END,
    to_node.branch_key
FROM workflow_node from_node
JOIN workflow_node to_node
    ON to_node.chain_id = from_node.chain_id
WHERE to_node.step_order = (
    SELECT MIN(next_node.step_order)
    FROM workflow_node next_node
    WHERE next_node.chain_id = from_node.chain_id
      AND next_node.step_order > from_node.step_order
);
