import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import '@fontsource/lora/latin-400.css'
import '@fontsource/lora/latin-600.css'
import '@fontsource/plus-jakarta-sans/latin-400.css'
import '@fontsource/plus-jakarta-sans/latin-500.css'
import '@fontsource/plus-jakarta-sans/latin-600.css'
import '@fontsource/plus-jakarta-sans/latin-700.css'
import { createApp } from 'vue'
import App from './App.vue'
import './styles.css'
import './factory-portal.css'
import './cs-portal.css'
import './cs-rebuilt-pages.css'
import './doctor-portal.css'
import './admin-portal.css'
import './admin-order-page.css'
import './doctor/doctor-portal-v2.css'

createApp(App).use(ElementPlus).mount('#app')
